run:
  concurrency: 4
  timeout: 5m
  tests: false
output:
  formats:
    - format: colored-line-number
  print-issued-lines: false

issues:
  exclude-dirs:
    - generated
    - mocks
    - scratch
    - tests
  exclude-files:
    - ".*easyjson\\.go$"

linters-settings:
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100
  lll:
    line-length: 140
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 3
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 3
  gocritic:
    disabled-checks:
      - hugeParam
      - unnamedResult
      - exposedSyncMutex
      - commentedOutCode
    enabled-tags:
      - performance
      - style
      - experimental
  gosec:
    excludes:
      - G306
  stylecheck:
    checks: [ "all", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022" ]

linters:
  enable:
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - gas
    - prealloc
    - errcheck
    - exportloopref
    - gofmt
    - gomnd
    - noctx
    - whitespace
    - asciicheck
    - makezero
    - nestif
    - sqlclosecheck
    - promlinter